import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GraphQLClient, gql} from "graphql-request"
import Nav from '../components/Nav'
import BlogCard from '../components/BlogCard'

const graphcms = new GraphQLClient("https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cl9hecjwa0gsn01uj7mgtceh8/master")

const QUERY = gql`
  {
    posts {
      datePublished
      id
      slug
      title
      content {
        html
      }
      
      coverPhoto{
        url
      }
      
      author {
        name
        avatar {
          url
        }
      }
    }
  }
`

export async function getStaticProps() {
  const {posts} = await graphcms.request(QUERY)
  return {
    props: {
      posts,
    },
  }
}

export default function Home({posts}) {
  return (
    <div className='m-8 lg:mx-44'>
      <Head>
        <title>Daily Captures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,700&family=Prata&display=swap" rel="stylesheet"></link>
        <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css" />
      </Head>

      <Nav />

      <main className='text-left pt-8 lg:pt-12 lg:pb-8'>     
        <div>
          <h1 className='text-4xl sm:text-5xl lg:text-6xl mt-4 lg:mt-0'>My daily captures</h1>
            {posts.map(post => (
              <BlogCard 
                key={post.id} 
                post={post}
              /> 
            ))} 
        </div> 
          
      </main>
    </div>
  )
}
