import Head from "next/head"
import Nav from "./Nav"

export const Layout = ({children}) => {
  return (
    <div className='m-8 lg:mx-48'>
        <Head>
            <title>My Travel Logs</title>
            <meta name="personal travel blog template" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        {children}
    </div>
  )
}
