import Head from "next/head"
import Nav from "./Nav"

export const Layout = ({children}) => {
  return (
    <div className='m-8 lg:mx-44'>
        <Head>
            <title>Daily Captures</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,700&family=Prata&display=swap" rel="stylesheet"></link>
            <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css" />
        </Head>
        <Nav />
        {children}
    </div>
  )
}
